# Generated by Django 5.2.6 on 2025-10-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailedapplication",
            name="ceo_comment",
            field=models.TextField(blank=True, verbose_name="CEO Interview Comment"),
        ),
        migrations.AddField(
            model_name="detailedapplication",
            name="ceo_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="detailedapplication",
            name="hr_comment",
            field=models.TextField(blank=True, verbose_name="HR Interview Comment"),
        ),
        migrations.AddField(
            model_name="detailedapplication",
            name="hr_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="detailedapplication",
            name="overall_status",
            field=models.CharField(
                choices=[
                    ("review", "In Review"),
                    ("hired", "Hired"),
                    ("rejected", "Rejected"),
                ],
                default="review",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="detailedapplication",
            name="phone_comment",
            field=models.TextField(blank=True, verbose_name="Phone Interview Comment"),
        ),
        migrations.AddField(
            model_name="detailedapplication",
            name="phone_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="detailedapplication",
            name="technical_comment",
            field=models.TextField(
                blank=True, verbose_name="Technical Interview Comment"
            ),
        ),
        migrations.AddField(
            model_name="detailedapplication",
            name="technical_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
