# Generated by Django 5.2.7 on 2025-11-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_detailedapplication_ceo_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedapplication',
            name='ceo_comment',
            field=models.TextField(blank=True, null=True, verbose_name='CEO Interview Comment'),
        ),
        migrations.AlterField(
            model_name='detailedapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailedapplication',
            name='hr_comment',
            field=models.TextField(blank=True, null=True, verbose_name='HR Interview Comment'),
        ),
        migrations.AlterField(
            model_name='detailedapplication',
            name='phone_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Phone Interview Comment'),
        ),
        migrations.AlterField(
            model_name='detailedapplication',
            name='technical_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Technical Interview Comment'),
        ),
    ]
