# Generated by Django 5.2.7 on 2025-11-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_cvsubmission_is_seen_detailedapplication_is_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvsubmission',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='detailedapplication',
            name='is_seen',
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailedapplication',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
