# Generated by Django 5.2.7 on 2025-11-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_cvsubmission_is_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsubmission',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailedapplication',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
