# Generated by Django 5.2.7 on 2025-11-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_cvsubmission_is_seen_detailedapplication_is_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvsubmission',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='detailedapplication',
            name='is_seen',
        ),
    ]
