# Generated by Django 5.2.7 on 2025-11-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_cvsubmission_is_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsubmission',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Operations', 'Operations')], default='HR', max_length=50),
        ),
    ]
