# Generated by Django 5.2.7 on 2025-11-05 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_cvsubmission_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsubmission',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='jobs.job'),
        ),
    ]
