# Generated by Django 5.2.7 on 2025-11-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_delete_generalcv'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=150)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('cv_file', models.FileField(upload_to='general_cvs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
