# Generated by Django 5.2.7 on 2025-11-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_generalcv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralCV',
        ),
    ]
