# Generated by Django 5.2.7 on 2025-11-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_delete_generalcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, choices=[('marketing', 'Marketing'), ('hr', 'Human Resources'), ('it', 'Information Technology'), ('finance', 'Finance'), ('sales', 'Sales'), ('production', 'Production')], max_length=50, null=True),
        ),
    ]
