# Generated by Django 5.2.7 on 2025-11-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_job_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of the next interview', null=True),
        ),
    ]
