# Generated by Django 5.2.7 on 2025-11-25 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_detailedapplication_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlink',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_links', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='cvsubmission',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='jobs.job'),
        ),
    ]
