# Generated by Django 5.2.7 on 2025-12-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_interviewslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewSlot',
        ),
    ]
